---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  taosks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml

